### ISSUE TITLE
可以提交到 firefox 吗

### ISSUE THREAD

**Issue by aimuz** [Figma-Cool/figmaCN#125]
目前为了安装这个插件注册了个开发者账号，将 FigmaCN 提交到 firefox 签名后才能安装，希望开发者可以注册一个firefox 开发者账号，然后将这个插件提交上去

我测试了一下，firefox 可以不做任何修改就可以支持。

**Comment by pluwen** [comment]
我们考虑下

**Comment by normal-coder** [comment]
Firefox 的附加组件的确是需要通过应用市场才能满足签名。
#127

**Comment by aimuz** [comment]
看来已经解决了，那我关闭这个问题吧
