### ISSUE TITLE
[BUG] 汉化插件误汉化了本地变量的内容

### ISSUE THREAD

**Issue by shaoLian-LH** [Figma-Cool/figmaCN#143]
# 背景
我在 Figma 中有使用到 local variables 这个功能，在创建变量的时候，变量名称在部分情况会被“汉化”，有办法避免这种情况出现吗？
以下是一组例子：

# 示例
1. 当我取名为 “color-click” 的时候，表现正常：
![color-click 结果](https://github.com/Figma-Cool/figmaCN/assets/49679679/2735abef-fdc6-44b0-a02c-5a7b2db3a17a)

2. 当我取名为 “function-color-click” 的时候，出现了不期待的汉化：
![function-color-click结果](https://github.com/Figma-Cool/figmaCN/assets/49679679/1f1eb1f0-a627-4e62-89a9-53204e5627df)

# 期望
插件能在一些特定内容上跳过不应该汉化的内容吗 Orz

**Comment by pluwen** [comment]
暂时不能

**Comment by shaoLian-LH** [comment]
那是后续有计划吗？或者说是可以 PR 🤔️

**Comment by shaoLian-LH** [comment]
本地 Chrome 进行测试后正常，麻烦 review

https://github.com/Figma-Cool/figmaCN/pull/144
