### ISSUE TITLE
发现遗漏的翻译点

### ISSUE THREAD

**Issue by yamazakitouma** [Figma-Cool/figmaCN#166]
<img width="456" alt="image" src="https://github.com/user-attachments/assets/e45d5397-a676-45bc-af34-aa487e31d409">
<img width="657" alt="image" src="https://github.com/user-attachments/assets/de64ccc7-49e5-4aec-a9a9-993c325b0217">
<img width="678" alt="image" src="https://github.com/user-attachments/assets/03b9cfa4-5aa0-4db7-8981-a7e7f4c13e13">

当前使用版本：1.2.3

**Comment by yamazakitouma** [comment]
@pluwen

**Comment by pluwen** [comment]
手动安装试试看，更新了

**Comment by yamazakitouma** [comment]
> 更新了下，手动下载仓库，用上去看看 确认没问题再发布版本

哥！你太效率了！

**Comment by yamazakitouma** [comment]
> 更新了下，手动下载仓库，用上去看看 确认没问题再发布版本

替换翻译的js试了，没有问题！正常！

**Comment by pluwen** [comment]
已发包
