### ISSUE TITLE
反馈翻译缺少

### ISSUE THREAD

**Issue by yamazakitouma** [Figma-Cool/figmaCN#169]
版本：1.2.4

<img width="251" alt="image" src="https://github.com/user-attachments/assets/c13787a4-38b5-4cf8-bdc8-7306c2aa6aea">
<img width="286" alt="image" src="https://github.com/user-attachments/assets/d99c4ddc-d86d-4548-9745-2547b77f66c9">
<img width="193" alt="image" src="https://github.com/user-attachments/assets/7df83b5e-dd71-47eb-8045-efa3d4fdce61">
<img width="522" alt="image" src="https://github.com/user-attachments/assets/cc304a0a-0dc5-48d0-a875-8bb0eaecc34a">
<img width="271" alt="image" src="https://github.com/user-attachments/assets/280d1203-6f97-4400-85f7-73f9bbeced71">
<img width="267" alt="image" src="https://github.com/user-attachments/assets/a608d3c7-3035-466e-b6f4-6e64fd86cb4a">
<img width="492" alt="image" src="https://github.com/user-attachments/assets/adb0dc71-7df3-4d75-8cf8-b4850e62b977">
<img width="647" alt="image" src="https://github.com/user-attachments/assets/4ec6df93-dec3-4eb4-888e-d771bc721d15">
<img width="485" alt="image" src="https://github.com/user-attachments/assets/0e9aa77d-d40e-4464-a126-ee65b79d1786">
<img width="219" alt="image" src="https://github.com/user-attachments/assets/a6bffd14-da2d-4ba7-bcd4-9b9ac89f5401">
<img width="418" alt="image" src="https://github.com/user-attachments/assets/aa324e88-fef9-4ccd-b83c-1c268e85a70b">
<img width="277" alt="image" src="https://github.com/user-attachments/assets/0281fa44-182f-4d1c-9399-0155fdf5bfa0">
<img width="299" alt="image" src="https://github.com/user-attachments/assets/fd69ee66-8a15-425d-a9f9-b173713675c8">

我自己尝试在本地的 content.js 中添加条目，不知为何不生效。

**Comment by pluwen** [comment]
大小写敏感，有时会有空格，标点符号也得小心
晚一点处理

**Comment by yamazakitouma** [comment]
> 大小写敏感，有时会有空格，标点符号也得小心 晚一点处理

是标点符号格式错了，核对后OK了，不用麻烦你了，我来改后提交。

**Comment by pluwen** [comment]
好嘞，发个pr，我合并

**Comment by yamazakitouma** [comment]
https://github.com/Figma-Cool/figmaCN/pull/170

已经提交请求，但是发现有部分内容仍然出现了汉化不了的情况，主要是 
![image](https://github.com/user-attachments/assets/8a7281e6-7ad4-4cfd-a277-4410a29f5fc2)
![image](https://github.com/user-attachments/assets/b821190d-225e-4cdf-8d6e-12b6ce06d6ab)
![image](https://github.com/user-attachments/assets/8886bb5a-99c0-4260-a6ae-793fc83552fc)
![image](https://github.com/user-attachments/assets/9f732b44-0284-49f3-a1b2-08ea20eb3187)

辛苦在核查下原因
